name: hello_job

on:
  push:
   branches:
     - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Run a one-line script

      run: echo Hello, world!

    - name: java version

      run: java -version

    - name: maven version

      run: mvn --version

    - name: python version

      run: python --version

